export const FOLIO_TYPES = [
  {
    id: 'baseball_cards',
    label: 'Baseball Cards',
    icon: '⚾',
    description: 'Players, sets, and eras',
    suggestedHalls: [
      { name: 'By Era', suggestedExhibits: ['Dead Ball Era', '1950s', '1960s', '1970s', '1980s', '1990s', '2000s', 'Modern'] },
      { name: 'By Team', suggestedExhibits: ['Yankees', 'Red Sox', 'Cubs', 'Dodgers', 'Cardinals'] },
      { name: 'By Brand', suggestedExhibits: ['Topps', 'Bowman', 'Fleer', 'Donruss', 'Upper Deck'] },
      { name: 'Rookies', suggestedExhibits: ['Hall of Famers', 'Active Stars', 'Prospects'] },
    ],
    suggestedFields: [
      { field_name: 'Player Name', field_type: 'text' },
      { field_name: 'Year', field_type: 'number' },
      { field_name: 'Brand', field_type: 'text' },
      { field_name: 'Card Number', field_type: 'text' },
      { field_name: 'Condition', field_type: 'text' },
      { field_name: 'Estimated Value', field_type: 'number' },
      { field_name: 'Graded', field_type: 'text' },
      { field_name: 'Grade Score', field_type: 'text' },
    ],
  },
  {
    id: 'vinyl_records',
    label: 'Vinyl Records',
    icon: '🎵',
    description: 'Albums, pressings, and artists',
    suggestedHalls: [
      { name: 'By Genre', suggestedExhibits: ['Jazz', 'Blues', 'Rock', 'Soul', 'Classical', 'Electronic', 'Hip Hop'] },
      { name: 'By Decade', suggestedExhibits: ['1950s', '1960s', '1970s', '1980s', '1990s'] },
      { name: 'Original Pressings', suggestedExhibits: ['First Press', 'Limited Edition', 'Colored Vinyl'] },
    ],
    suggestedFields: [
      { field_name: 'Artist', field_type: 'text' },
      { field_name: 'Album Title', field_type: 'text' },
      { field_name: 'Year', field_type: 'number' },
      { field_name: 'Label', field_type: 'text' },
      { field_name: 'Pressing', field_type: 'text' },
      { field_name: 'Condition', field_type: 'text' },
      { field_name: 'Estimated Value', field_type: 'number' },
    ],
  },
  {
    id: 'coins',
    label: 'Coins & Currency',
    icon: '🪙',
    description: 'Coins, banknotes, and bullion',
    suggestedHalls: [
      { name: 'By Country', suggestedExhibits: ['United States', 'Ancient Rome', 'British Empire', 'World Coins'] },
      { name: 'By Era', suggestedExhibits: ['Ancient', 'Medieval', 'Early Modern', 'Modern'] },
      { name: 'By Type', suggestedExhibits: ['Gold', 'Silver', 'Copper', 'Banknotes'] },
    ],
    suggestedFields: [
      { field_name: 'Country', field_type: 'text' },
      { field_name: 'Year', field_type: 'number' },
      { field_name: 'Denomination', field_type: 'text' },
      { field_name: 'Mint Mark', field_type: 'text' },
      { field_name: 'Composition', field_type: 'text' },
      { field_name: 'Condition / Grade', field_type: 'text' },
      { field_name: 'Estimated Value', field_type: 'number' },
    ],
  },
  {
    id: 'meteorites',
    label: 'Meteorites',
    icon: '☄️',
    description: 'Specimens, falls, and finds',
    suggestedHalls: [
      { name: 'By Classification', suggestedExhibits: ['Chondrites', 'Achondrites', 'Iron', 'Stony-Iron', 'Pallasite'] },
      { name: 'By Origin', suggestedExhibits: ['Mars', 'Moon', 'Asteroid Belt', 'Unknown'] },
      { name: 'Notable Falls', suggestedExhibits: ['Witnessed Falls', 'Historic Finds', 'Named Falls'] },
    ],
    suggestedFields: [
      { field_name: 'Classification', field_type: 'text' },
      { field_name: 'Find or Fall', field_type: 'text' },
      { field_name: 'Year Found', field_type: 'number' },
      { field_name: 'Location Found', field_type: 'text' },
      { field_name: 'Weight (g)', field_type: 'number' },
      { field_name: 'Composition', field_type: 'text' },
      { field_name: 'Associated Fall', field_type: 'text' },
      { field_name: 'Estimated Value', field_type: 'number' },
    ],
  },
  {
    id: 'movies',
    label: 'Movies',
    icon: '🎬',
    description: 'Films, directors, and genres',
    suggestedHalls: [
      { name: 'By Genre', suggestedExhibits: ['Horror', 'Sci-Fi', 'Comedy', 'Drama', 'Action', 'Documentary'] },
      { name: 'By Decade', suggestedExhibits: ['1940s', '1950s', '1960s', '1970s', '1980s', '1990s', '2000s'] },
      { name: 'By Director', suggestedExhibits: ['Kubrick', 'Scorsese', 'Spielberg', 'Tarantino', 'Hitchcock'] },
    ],
    suggestedFields: [
      { field_name: 'Title', field_type: 'text' },
      { field_name: 'Year', field_type: 'number' },
      { field_name: 'Director', field_type: 'text' },
      { field_name: 'Genre', field_type: 'text' },
      { field_name: 'Rating', field_type: 'text' },
      { field_name: 'Personal Rating', field_type: 'number' },
      { field_name: 'Format Owned', field_type: 'text' },
    ],
  },
  {
    id: 'sneakers',
    label: 'Sneakers',
    icon: '👟',
    description: 'Kicks, colorways, and collabs',
    suggestedHalls: [
      { name: 'By Brand', suggestedExhibits: ['Nike', 'Jordan', 'Adidas', 'New Balance', 'Asics'] },
      { name: 'By Style', suggestedExhibits: ['Running', 'Basketball', 'Lifestyle', 'Collaborations'] },
      { name: 'By Year', suggestedExhibits: ['Vintage', '1990s', '2000s', 'Modern'] },
    ],
    suggestedFields: [
      { field_name: 'Brand', field_type: 'text' },
      { field_name: 'Model', field_type: 'text' },
      { field_name: 'Colorway', field_type: 'text' },
      { field_name: 'Size', field_type: 'text' },
      { field_name: 'Year Released', field_type: 'number' },
      { field_name: 'Condition', field_type: 'text' },
      { field_name: 'Retail Price', field_type: 'number' },
      { field_name: 'Current Value', field_type: 'number' },
    ],
  },
  {
    id: 'comic_books',
    label: 'Comic Books',
    icon: '💥',
    description: 'Issues, runs, and first appearances',
    suggestedHalls: [
      { name: 'By Publisher', suggestedExhibits: ['Marvel', 'DC', 'Image', 'Dark Horse', 'Indie'] },
      { name: 'By Era', suggestedExhibits: ['Golden Age', 'Silver Age', 'Bronze Age', 'Modern Age'] },
      { name: 'Key Issues', suggestedExhibits: ['First Appearances', 'Death Issues', 'Origin Stories'] },
    ],
    suggestedFields: [
      { field_name: 'Title', field_type: 'text' },
      { field_name: 'Issue Number', field_type: 'text' },
      { field_name: 'Publisher', field_type: 'text' },
      { field_name: 'Year', field_type: 'number' },
      { field_name: 'Condition', field_type: 'text' },
      { field_name: 'Key Issue Notes', field_type: 'text' },
      { field_name: 'Estimated Value', field_type: 'number' },
    ],
  },
  {
    id: 'watches',
    label: 'Watches',
    icon: '⌚',
    description: 'Timepieces, movements, and makers',
    suggestedHalls: [
      { name: 'By Brand', suggestedExhibits: ['Rolex', 'Omega', 'Patek Philippe', 'Seiko', 'Vintage'] },
      { name: 'By Movement', suggestedExhibits: ['Automatic', 'Manual Wind', 'Quartz', 'Digital'] },
      { name: 'By Style', suggestedExhibits: ['Dress', 'Dive', 'Pilot', 'Field', 'Chronograph'] },
    ],
    suggestedFields: [
      { field_name: 'Brand', field_type: 'text' },
      { field_name: 'Model', field_type: 'text' },
      { field_name: 'Reference Number', field_type: 'text' },
      { field_name: 'Year', field_type: 'number' },
      { field_name: 'Movement Type', field_type: 'text' },
      { field_name: 'Case Material', field_type: 'text' },
      { field_name: 'Condition', field_type: 'text' },
      { field_name: 'Estimated Value', field_type: 'number' },
    ],
  },
  {
    id: 'custom',
    label: 'Custom',
    icon: '✨',
    description: 'Build your own from scratch',
    suggestedHalls: [],
    suggestedFields: [],
  },
]